### ISSUE TITLE
如何在coco annotator使用半自动标注？

### ISSUE THREAD

**Issue by zyc460691495** [master686/Semi-supervised-keypoint-annotate-server-for-COCO-Annotator#2]
我在image setting中配置了url，并没有效果，查看了官方的文档和网上的资料，对自动标注的配置介绍的很少，请问您是如何使用的？

**Comment by zyc460691495** [comment]
谢谢您提供的代码，我已经大致理解了自动标注的流程

**Comment by zyc460691495** [comment]
主要是对于返回的标注的格式具体格式有什么要求呢？

**Comment by zyc460691495** [comment]
你好，我可以同时支持bbox和关键点的标注，还需要吗？

**Comment by ShuPengGitHub** [comment]
In USAGE, there have python simple_request.py words, where can I get the simple_request.py file?

**Comment by zyc460691495** [comment]
> In USAGE, there have python simple_request.py words, where can I get the simple_request.py file
只要按照需要的格式，返回标注信息就行了
